### ISSUE TITLE
Nullpointer exception with latest Spigot build

### ISSUE THREAD

**Issue by Swede37** [Yamakaja/rpgpets#9]
using RPGpets 1.1.17 and Spigot-2086bb0-ca057a3 (MC: 1.12.2)
https://pastebin.com/2LYhU7ms

**Comment by Swede37** [comment]
OK, as an update - I seem to be having some issues with this latest Spigot build - I don't think this is RPGpets as much as the current build of Spigot. Closing this until I can check the future Spigot build.

**Comment by Yamakaja** [comment]
Fixed in the next release, weird that it didn't come up until now 0.o

**Comment by Swede37** [comment]
Yeah, it's a weird one.  When my pet hatched, I got the Head for a chicken in my inventory, but when I tried to place it down it placed as a head. XD

**Comment by Yamakaja** [comment]
Alright, fix is out
